{% set name = "vault" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 5f3e4dd0cd1f4cb1e4fc4be38a4839d8683bad62ad5b7a68f1e49f545750b42b  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: 55b38c5010726c310e01fc797a62e7c466aa2f439c4d27ff3cf872b0298baeda  # [win64]

build:
  number: 1

requirements:
  build:
    - make  # [not win]
    - {{ compiler('c') }}
  host:
    - go 1.10.*  # [not win]
    - git  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
