{% set import_path = "github.com/hashicorp/vault" %}
{% set version = "1.1.3" %}

{% set name = import_path.split('/')[-1] %}
{% set pkg_src = 'src' + os.sep+ import_path.replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    git_url: https://{{ import_path }}
    git_tag: v{{version}}

build:
  number: 1
  script:
    - pushd {{ pkg_src }}
    - make static-dist
    - go install -v -tags="ui" .

requirements:
  build:
    - {{ compiler('go') }}
    - go-bindata-assetfs
    - go-gox
    - make
    - yarn

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://www.vaultproject.io
  license: MPL 2.0
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html

extra:
  recipe-maintainers:
    - johanneskoester
    - sodre
    - adbeda
