{% set version = "1.20.4" %}

package:
  name: vault
  version: {{ version }}

source:
  - url: https://github.com/hashicorp/vault/archive/v{{ version }}.tar.gz
    sha256: ae2215a325145c824c0f2bfdedcdd7cef44402b0eb3107a30133b82bb42d0403

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - vault --help

about:
  home: https://www.vaultproject.io
  license: MPL-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: A tool for managing secrets.
  description: |
    Vault is a tool for securely accessing secrets. A secret is anything that you
    want to tightly control access to, such as API keys, passwords, certificates,
    and more. Vault provides a unified interface to any secret, while providing
    tight access control and recording a detailed audit log.
  doc_url: https://www.vaultproject.io/docs/index.html
  dev_url: https://github.com/hashicorp/vault.git

extra:
  recipe-maintainers:
    - danielnachun
    - mxr-conda
    - johanneskoester
    - sodre
    - mariusvniekerk
    - oblute
    - JennaLipscomb
