appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Mi2XWzawAxbnYwa+ub2G6NKHMvCfBjkpQMNv/lD/2Vb2krafjM8n0ewqLyZXciJ6w1e0hO/s+Vsb5+5K/0TXxmCcXWC3UHebUgiVhSTIZs8k0lSGVC1YO4Lh+D3J5FXBhYTevhrF/2I5/ELmJnsP/lOiRZOswPVFlM5AZxKz9OCoLWTQCDZxu10fkbiRJJZYOhkaN9yy6pWFBE431Ji/CzeZYbL/XTbYmIgCirq+KGytXpB5Qa5uUqfGrqyfnk8YnYpVf8Qer3jMZmaOFqqwunJzARMzBDQlcZ5+G2+PM6An4kgv/y0F0dfWC0U5M9Yisx61gClCTrdfYYs94YU7tjFigrTqSObcOH/ZWzqS8Rck8ed3AuB6mpl5wixR/ZqP+H+uDLOwZEOQQREoatorHLKXfRzQvijiVCY/jNqngMeb0fbvqsDGyKsW333M840MmChY18OqXOlpON699YRNAXxdHQqv3MrfLpNTvGfOOWUqemxCNwIG54CSImMcD8gIg2nRXHp42/jmaB15Kn4E9bR0FJpZiVHpkqYNPHGvJiM+B8/iVRA2s3oZZoevOS2dm1g8g7CspZpN4X2fTuPVZMxcSLJdkWraLg2sU4dZiEiWFp9B4/ZZ+ZEC4Fp0B0dnp4dVEBz0KTTgC3XsRclgSuy2xVdWGs6rtoOwUaxIxGc=}
